/*
  # Add Extended Product Fields + Seed All Products

  1. Schema Changes
    - Add `benefits` (TEXT[]) column to products
    - Add `key_features` (TEXT[]) column to products
    - Add UNIQUE constraint on `sku` for upsert safety
    - Change `id` to accept string-type SKU values (already TEXT PRIMARY KEY)

  2. Seed Data
    - Insert all 34 CoreForge products
    - Uses ON CONFLICT (sku) DO NOTHING for idempotency

  3. Notes
    - Products use TEXT primary keys matching their SKU codes (CFG-001 etc)
    - Image paths reference local /other/supp-images/ folder
*/

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS benefits TEXT[] DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS key_features TEXT[] DEFAULT ARRAY[]::TEXT[];

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS long_description TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_name = 'products' AND constraint_name = 'products_sku_unique'
  ) THEN
    ALTER TABLE public.products ADD CONSTRAINT products_sku_unique UNIQUE (sku);
  END IF;
END $$;

INSERT INTO products (
  id, name, slug, description, long_description, sku, category,
  price, compare_at_price, image, images,
  stock_quantity, rating, review_count, badge, is_featured, is_active,
  track_inventory, continue_selling_when_out_of_stock, requires_shipping,
  weight_g, servings, flavor, size,
  nutrition_facts, ingredients, usage_instructions, warnings, allergens,
  benefits, key_features, created_at, updated_at
) VALUES

-- PROTEIN POWDERS
(
  'CFG-001', 'CoreForge Whey Protein 2kg (Chocolate)',
  'whey-protein-2kg-chocolate',
  'Premium whey protein concentrate with 24g protein per serve. Perfect for muscle growth and recovery.',
  'CoreForge Whey Protein delivers 24 grams of high-quality protein per serving to support muscle growth, recovery, and maintenance. Made from premium whey concentrate, this chocolate-flavored protein powder mixes easily and tastes great. Ideal for post-workout recovery or anytime you need a protein boost.',
  'CFG-001', 'Protein Powders',
  119.00, NULL,
  '/other/supp-images/CFG-001_119 — CoreForge Whey Protein 2kg (Chocolate).png',
  '["/other/supp-images/CFG-001_119 — CoreForge Whey Protein 2kg (Chocolate).png"]'::jsonb,
  150, 4.8, 342, 'Best Seller', true, true,
  true, false, true,
  2000, 66, 'Chocolate', '2kg',
  '{"servingSize":"30g","servingsPerContainer":66,"calories":120,"protein":"24g","carbs":"3g","fat":"2g"}'::jsonb,
  ARRAY['Whey Protein Concentrate','Cocoa Powder','Natural Flavors','Sucralose','Soy Lecithin'],
  'Mix 1 scoop (30g) with 200-300ml of water or milk. Consume 1-3 times daily, ideally post-workout or between meals.',
  'Not suitable for those with milk allergies. Consult a healthcare professional before use if pregnant or nursing.',
  ARRAY['Milk','Soy'],
  ARRAY['Supports muscle growth and recovery','24g high-quality protein per serve','Fast absorption for post-workout','Great taste and mixability','Low carb and low fat'],
  ARRAY['Premium Whey Concentrate','Fast Absorbing','Low Sugar','66 Servings'],
  NOW(), NOW()
),
(
  'CFG-009', 'CoreForge Whey Protein 1.5kg',
  'whey-protein-1-5kg',
  'Same premium formula in a convenient 1.5kg size. Perfect for trying or lighter users.',
  'All the benefits of our flagship whey protein in a smaller, more manageable size. Perfect for those who want to try CoreForge or prefer a smaller tub.',
  'CFG-009', 'Protein Powders',
  99.00, NULL,
  '/other/supp-images/CFG-009_99 — CoreForge Whey Protein 1.5kg.png',
  '["/other/supp-images/CFG-009_99 — CoreForge Whey Protein 1.5kg.png"]'::jsonb,
  120, 4.8, 198, 'Best Seller', true, true,
  true, false, true,
  1500, 50, NULL, '1.5kg',
  '{"servingSize":"30g","servingsPerContainer":50,"calories":120,"protein":"24g","carbs":"3g","fat":"2g"}'::jsonb,
  NULL, 'Mix 1 scoop (30g) with 200-300ml of water or milk.', 'Contains milk and soy.', ARRAY['Milk','Soy'],
  ARRAY['Same premium formula','Convenient smaller size','24g protein per serve','Perfect for trying CoreForge'],
  ARRAY['Premium Whey','50 Servings','Multiple Flavors','Great Value'],
  NOW(), NOW()
),
(
  'CFG-005', 'CoreForge Whey Isolate 2.5kg',
  'whey-isolate-2-5kg',
  '90%+ pure protein isolate. Ultra-low lactose, fast absorption for serious athletes.',
  'CoreForge Whey Isolate is our purest protein formula, containing over 90% protein by weight. With minimal lactose, fats, and carbs, this is perfect for those who want pure protein without the extras. Ideal for cutting phases or lactose-sensitive individuals.',
  'CFG-005', 'Protein Powders',
  179.00, NULL,
  '/other/supp-images/CFG-005_179 — CoreForge Whey Isolate 2.5kg.png',
  '["/other/supp-images/CFG-005_179 — CoreForge Whey Isolate 2.5kg.png"]'::jsonb,
  85, 4.9, 267, 'Athlete Approved', true, true,
  true, false, true,
  2500, 83, NULL, '2.5kg',
  '{"servingSize":"30g","servingsPerContainer":83,"calories":110,"protein":"27g","carbs":"1g","fat":"0.5g"}'::jsonb,
  NULL, 'Mix 1 scoop with 250ml water.', 'Contains milk.', ARRAY['Milk'],
  ARRAY['90%+ pure protein','Ultra-low lactose','Minimal carbs and fats','Fast absorption','Perfect for cutting'],
  ARRAY['Whey Isolate','27g Protein','Low Lactose','83 Servings'],
  NOW(), NOW()
),
(
  'CFG-032', 'CoreForge Whey Isolate 2kg',
  'whey-isolate-2kg',
  'Premium isolate formula in a 2kg tub. Pure protein for maximum results.',
  'The same ultra-pure whey isolate formula in our popular 2kg size. Perfect for those who want the benefits of isolate without committing to the larger tub.',
  'CFG-032', 'Protein Powders',
  169.00, NULL,
  '/other/supp-images/CFG-032_169 — CoreForge Whey Isolate 2kg.png',
  '["/other/supp-images/CFG-032_169 — CoreForge Whey Isolate 2kg.png"]'::jsonb,
  95, 4.9, 183, NULL, false, true,
  true, false, true,
  2000, 66, NULL, '2kg',
  '{"servingSize":"30g","servingsPerContainer":66,"calories":110,"protein":"27g","carbs":"1g","fat":"0.5g"}'::jsonb,
  NULL, NULL, NULL, NULL,
  ARRAY['Pure isolate formula','27g protein per serve','Low carb and fat','Easy to digest'],
  ARRAY['90%+ Protein','Fast Absorbing','Low Lactose','66 Servings'],
  NOW(), NOW()
),
(
  'CFG-010', 'CoreForge Plant Protein 2kg',
  'plant-protein-2kg',
  'Complete vegan protein blend from pea, rice, and hemp. 100% plant-based excellence.',
  'CoreForge Plant Protein is a complete vegan protein blend combining pea, rice, and hemp proteins to deliver all essential amino acids. Perfect for vegans, vegetarians, or anyone looking to add more plant-based nutrition to their diet.',
  'CFG-010', 'Protein Powders',
  149.00, NULL,
  '/other/supp-images/CFG-010_149 — CoreForge Plant Protein 2kg.png',
  '["/other/supp-images/CFG-010_149 — CoreForge Plant Protein 2kg.png"]'::jsonb,
  110, 4.7, 156, 'New', true, true,
  true, false, true,
  2000, 66, NULL, '2kg',
  '{"servingSize":"30g","servingsPerContainer":66,"calories":115,"protein":"22g","carbs":"4g","fat":"2.5g"}'::jsonb,
  NULL, NULL, NULL, NULL,
  ARRAY['100% plant-based','Complete amino acid profile','Vegan and vegetarian friendly','Easy to digest','Sustainable protein source'],
  ARRAY['Pea + Rice + Hemp','22g Protein','Vegan','Complete Amino Acids'],
  NOW(), NOW()
),
(
  'CFG-020', 'CoreForge Vegan Protein Blend',
  'vegan-protein-blend',
  'Premium plant-based protein with added superfoods. Nourish your body naturally.',
  'An enhanced vegan protein formula with added superfoods like spirulina and chlorella for extra nutrition. Perfect for health-conscious individuals seeking more than just protein.',
  'CFG-020', 'Protein Powders',
  109.00, NULL,
  '/other/supp-images/CFG-020_109 — CoreForge Vegan Protein Blend.png',
  '["/other/supp-images/CFG-020_109 — CoreForge Vegan Protein Blend.png"]'::jsonb,
  75, 4.6, 89, 'New', false, true,
  true, false, true,
  1000, 33, NULL, '1kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Plant-based protein','Added superfoods','Complete nutrition','Sustainable'],
  ARRAY['Vegan','Superfoods','20g Protein','Eco-Friendly'],
  NOW(), NOW()
),
(
  'CFG-011', 'CoreForge Casein Protein 1kg',
  'casein-protein-1kg',
  'Slow-release protein for overnight recovery. Keep your muscles fed for hours.',
  'CoreForge Casein is a slow-digesting protein that provides a steady release of amino acids for up to 7 hours. Perfect for taking before bed to support overnight muscle recovery and prevent muscle breakdown.',
  'CFG-011', 'Protein Powders',
  79.00, NULL,
  '/other/supp-images/CFG-011_79 — CoreForge Casein Protein 1kg.png',
  '["/other/supp-images/CFG-011_79 — CoreForge Casein Protein 1kg.png"]'::jsonb,
  90, 4.7, 134, NULL, false, true,
  true, false, true,
  1000, 33, NULL, '1kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Slow-release formula','Up to 7 hours of protein delivery','Perfect for before bed','Prevents muscle breakdown'],
  ARRAY['Micellar Casein','Slow Digestion','24g Protein','Night Recovery'],
  NOW(), NOW()
),
(
  'CFG-023', 'CoreForge Casein Protein 2kg (Vanilla Bean)',
  'casein-protein-2kg-vanilla',
  'Our premium casein in a delicious vanilla flavor. Larger size for serious users.',
  'The same slow-release casein protein in our popular vanilla bean flavor. This larger 2kg tub is perfect for those who use casein regularly for overnight recovery.',
  'CFG-023', 'Protein Powders',
  149.00, NULL,
  '/other/supp-images/CFG-023_149 — CoreForge Casein Protein 2kg (Vanilla Bean).png',
  '["/other/supp-images/CFG-023_149 — CoreForge Casein Protein 2kg (Vanilla Bean).png"]'::jsonb,
  65, 4.8, 97, NULL, false, true,
  true, false, true,
  2000, 66, 'Vanilla Bean', '2kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Slow digestion','Vanilla flavor','Great value size','Overnight recovery'],
  ARRAY['Micellar Casein','25g Protein','Vanilla','66 Servings'],
  NOW(), NOW()
),
(
  'CFG-023B', 'CoreForge Casein Protein 2kg (Chocolate)',
  'casein-protein-2kg-chocolate',
  'Rich chocolate casein for nighttime recovery. Tastes like dessert, works like science.',
  'Our premium casein protein in a rich chocolate flavor. Perfect as a nighttime treat that supports muscle recovery while you sleep.',
  'CFG-023B', 'Protein Powders',
  149.00, NULL,
  '/other/supp-images/CFG-023B_149 — CoreForge Casein Protein 2kg (Chocolate).png',
  '["/other/supp-images/CFG-023B_149 — CoreForge Casein Protein 2kg (Chocolate).png"]'::jsonb,
  70, 4.8, 112, NULL, false, true,
  true, false, true,
  2000, 66, 'Chocolate', '2kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Rich chocolate taste','Slow-release protein','Perfect before bed','Anti-catabolic'],
  ARRAY['Micellar Casein','25g Protein','Chocolate','66 Servings'],
  NOW(), NOW()
),
(
  'CFG-034', 'CoreForge Night Recovery Casein',
  'night-recovery-casein',
  'Enhanced casein formula with added recovery nutrients for optimal overnight gains.',
  'An enhanced casein formula with added glutamine, magnesium, and zinc to support deeper sleep and faster recovery. Your complete nighttime recovery solution.',
  'CFG-034', 'Protein Powders',
  79.00, NULL,
  '/other/supp-images/CFG-034_79 — CoreForge Night Recovery Casein.png',
  '["/other/supp-images/CFG-034_79 — CoreForge Night Recovery Casein.png"]'::jsonb,
  55, 4.7, 78, NULL, false, true,
  true, false, true,
  1000, 33, NULL, '1kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Enhanced recovery formula','Added sleep support','Magnesium & zinc','Complete night nutrition'],
  ARRAY['Casein + Glutamine','Sleep Support','24g Protein','Recovery Minerals'],
  NOW(), NOW()
),
(
  'CFG-014', 'CoreForge Meal Replacement 1.5kg',
  'meal-replacement-1-5kg',
  'Complete nutrition in a shake. Balanced macros, vitamins, and minerals for on-the-go meals.',
  'CoreForge Meal Replacement is a complete nutrition solution with balanced protein, carbs, fats, plus 25 essential vitamins and minerals. Perfect for busy professionals or anyone needing a quick, nutritious meal.',
  'CFG-014', 'Protein Powders',
  119.00, NULL,
  '/other/supp-images/CFG-014_119 — CoreForge Meal Replacement 1.5kg.png',
  '["/other/supp-images/CFG-014_119 — CoreForge Meal Replacement 1.5kg.png"]'::jsonb,
  80, 4.6, 143, NULL, false, true,
  true, false, true,
  1500, 30, NULL, '1.5kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Complete meal in a shake','25 vitamins & minerals','Balanced macronutrients','Convenient nutrition','Supports weight management'],
  ARRAY['Complete Nutrition','20g Protein','25 Vitamins','30 Meals'],
  NOW(), NOW()
),
(
  'CFG-029', 'CoreForge Lean Protein 1kg',
  'lean-protein-1kg',
  'Ultra-lean protein formula perfect for cutting. Maximum protein, minimum calories.',
  'Designed specifically for cutting phases, this ultra-lean formula delivers maximum protein with absolute minimal carbs, fats, and calories. Get shredded without sacrificing muscle.',
  'CFG-029', 'Protein Powders',
  99.00, NULL,
  '/other/supp-images/CFG-029_99 — CoreForge Lean Protein 1kg.png',
  '["/other/supp-images/CFG-029_99 — CoreForge Lean Protein 1kg.png"]'::jsonb,
  100, 4.7, 91, NULL, false, true,
  true, false, true,
  1000, 33, NULL, '1kg',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Ultra-lean formula','Perfect for cutting','Maximum protein','Minimal calories'],
  ARRAY['Lean Blend','26g Protein','Low Calorie','Fat Loss Support'],
  NOW(), NOW()
),

-- PRE-WORKOUT
(
  'CFG-003', 'CoreForge Pre-Workout 30 Serves',
  'pre-workout-30-serves',
  'Explosive energy and focus for maximum performance. Crush your workouts every time.',
  'CoreForge Pre-Workout delivers explosive energy, laser focus, and powerful pumps to help you push through even the toughest workouts. With clinically-dosed ingredients including caffeine, beta-alanine, and citrulline malate.',
  'CFG-003', 'Pre-Workout',
  69.00, NULL,
  '/other/supp-images/CFG-003_69 — CoreForge Pre-Workout 30 Serves.png',
  '["/other/supp-images/CFG-003_69 — CoreForge Pre-Workout 30 Serves.png"]'::jsonb,
  200, 4.8, 287, 'Best Seller', true, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL,
  'Mix 1 scoop with 250ml of cold water 20-30 minutes before training. Start with half a serve to assess tolerance.',
  'Contains 200mg caffeine per serve. Not suitable for those sensitive to caffeine or under 18.',
  NULL,
  ARRAY['Explosive energy boost','Enhanced mental focus','Increased muscle pumps','Improved endurance','No crash or jitters'],
  ARRAY['200mg Caffeine','Beta-Alanine','Citrulline Malate','30 Servings'],
  NOW(), NOW()
),
(
  'CFG-015', 'CoreForge Advanced Pre-Workout 60 Serves',
  'advanced-pre-workout-60-serves',
  'Maximum strength formula for elite athletes. Double the servings, double the gains.',
  'Our most advanced pre-workout formula with higher doses of key ingredients for elite performance. This 60-serve tub offers exceptional value for serious athletes.',
  'CFG-015', 'Pre-Workout',
  179.00, NULL,
  '/other/supp-images/CFG-015_179 — CoreForge Advanced Pre-Workout 60 Serves.png',
  '["/other/supp-images/CFG-015_179 — CoreForge Advanced Pre-Workout 60 Serves.png"]'::jsonb,
  85, 4.9, 203, 'Athlete Approved', true, true,
  true, false, true,
  NULL, 60, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Maximum strength formula','Enhanced focus compounds','Sustained energy','Great value (60 serves)'],
  ARRAY['250mg Caffeine','Nootropic Blend','Premium Ingredients','60 Servings'],
  NOW(), NOW()
),
(
  'CFG-031', 'CoreForge Pump Matrix Pre-Workout',
  'pump-matrix-pre-workout',
  'Stimulant-free pump formula. Maximum blood flow and muscle fullness without caffeine.',
  'For those who train late or are sensitive to caffeine, Pump Matrix delivers incredible muscle pumps and vascularity without any stimulants. Perfect for evening training sessions.',
  'CFG-031', 'Pre-Workout',
  99.00, NULL,
  '/other/supp-images/CFG-031_99 — CoreForge Pump Matrix Pre-Workout.png',
  '["/other/supp-images/CFG-031_99 — CoreForge Pump Matrix Pre-Workout.png"]'::jsonb,
  70, 4.7, 124, NULL, false, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Stimulant-free','Maximum pumps','Perfect for evening training','Enhanced blood flow'],
  ARRAY['No Caffeine','Citrulline','Nitric Oxide Boost','Vascular Support'],
  NOW(), NOW()
),
(
  'CFG-033', 'CoreForge Hardcore Pre-Workout',
  'hardcore-pre-workout',
  'Extreme energy for extreme athletes. Not for beginners. Maximum intensity guaranteed.',
  'Our most potent pre-workout formula designed for advanced users who need maximum energy and focus. Contains 350mg caffeine plus additional stimulants. Only for experienced users.',
  'CFG-033', 'Pre-Workout',
  179.00, NULL,
  '/other/supp-images/CFG-033_179 — CoreForge Hardcore Pre-Workout.png',
  '["/other/supp-images/CFG-033_179 — CoreForge Hardcore Pre-Workout.png"]'::jsonb,
  45, 4.8, 167, 'Athlete Approved', false, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL,
  'EXTREME FORMULA. Contains 350mg caffeine. Only for advanced users. Not suitable for under 18 or those with heart conditions.',
  NULL,
  ARRAY['Maximum energy','Extreme focus','For advanced users','Peak performance'],
  ARRAY['350mg Caffeine','Advanced Stimulants','Max Intensity','Elite Formula'],
  NOW(), NOW()
),

-- CREATINE
(
  'CFG-002', 'CoreForge Creatine Monohydrate 500g',
  'creatine-monohydrate-500g',
  'Pure micronized creatine monohydrate. The most researched supplement for strength and power.',
  'CoreForge Creatine Monohydrate is 100% pure, micronized creatine monohydrate - the gold standard for increasing strength, power, and muscle mass. With over 500 studies supporting its effectiveness, creatine is a must-have for any serious athlete.',
  'CFG-002', 'Creatine',
  69.00, NULL,
  '/other/supp-images/CFG-002_69 — CoreForge Creatine Monohydrate 500g.png',
  '["/other/supp-images/CFG-002_69 — CoreForge Creatine Monohydrate 500g.png"]'::jsonb,
  250, 4.9, 412, 'Best Seller', true, true,
  true, false, true,
  500, 100, NULL, '500g',
  NULL, NULL,
  'Mix 5g (1 scoop) with water or your favorite beverage. Take daily, ideally post-workout.',
  NULL, NULL,
  ARRAY['Increases strength and power','Supports muscle growth','Improves high-intensity performance','100% pure monohydrate','Micronized for better absorption'],
  ARRAY['100% Pure','Micronized','5g Per Serve','100 Servings'],
  NOW(), NOW()
),
(
  'CFG-027', 'CoreForge Creatine 100g',
  'creatine-100g',
  'Trial size creatine. Perfect for first-time users to test the benefits.',
  'Try creatine for the first time with our 100g trial size. Same premium quality, smaller commitment. Perfect for testing if creatine works for you.',
  'CFG-027', 'Creatine',
  19.00, NULL,
  '/other/supp-images/CFG-027_19 — CoreForge Creatine 100g.png',
  '["/other/supp-images/CFG-027_19 — CoreForge Creatine 100g.png"]'::jsonb,
  300, 4.8, 87, 'New', false, true,
  true, false, true,
  100, 20, NULL, '100g',
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Perfect trial size','Same premium quality','Low commitment','Test the benefits'],
  ARRAY['100% Pure','Trial Size','20 Servings','Great Value'],
  NOW(), NOW()
),

-- RECOVERY & PERFORMANCE
(
  'CFG-008', 'CoreForge BCAA Recovery 30 Serves',
  'bcaa-recovery-30-serves',
  'Essential amino acids in a 2:1:1 ratio. Reduce soreness and accelerate recovery.',
  'CoreForge BCAA Recovery delivers leucine, isoleucine, and valine in the clinically-proven 2:1:1 ratio to reduce muscle soreness, prevent breakdown, and accelerate recovery between workouts.',
  'CFG-008', 'Recovery & Performance',
  69.00, NULL,
  '/other/supp-images/CFG-008_69 — CoreForge BCAA Recovery 30 Serves.png',
  '["/other/supp-images/CFG-008_69 — CoreForge BCAA Recovery 30 Serves.png"]'::jsonb,
  180, 4.7, 234, 'Best Seller', true, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Reduces muscle soreness','Prevents muscle breakdown','Accelerates recovery','2:1:1 BCAA ratio','Great tasting'],
  ARRAY['2:1:1 Ratio','7g BCAAs','Zero Sugar','30 Servings'],
  NOW(), NOW()
),
(
  'CFG-030', 'CoreForge Amino Energy Blend',
  'amino-energy-blend',
  'BCAAs plus energy. Perfect for anytime energy and recovery support.',
  'Combines essential amino acids with natural caffeine for a dual-purpose supplement. Use it pre-workout for energy, during workout for endurance, or post-workout for recovery.',
  'CFG-030', 'Recovery & Performance',
  89.00, NULL,
  '/other/supp-images/CFG-030_89 — CoreForge Amino Energy Blend.png',
  '["/other/supp-images/CFG-030_89 — CoreForge Amino Energy Blend.png"]'::jsonb,
  95, 4.6, 143, NULL, false, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['BCAAs plus energy','Versatile usage','Natural caffeine','Recovery support'],
  ARRAY['Aminos + Caffeine','Multi-Purpose','5g BCAAs','Natural Energy'],
  NOW(), NOW()
),
(
  'CFG-004', 'CoreForge Thermogenic Fat Burner',
  'thermogenic-fat-burner',
  'Advanced fat burning formula. Boost metabolism and energy while preserving muscle.',
  'CoreForge Thermogenic combines proven fat-burning ingredients like green tea extract, caffeine, and L-carnitine to help boost metabolism, increase energy expenditure, and support fat loss while preserving lean muscle mass.',
  'CFG-004', 'Recovery & Performance',
  79.00, NULL,
  '/other/supp-images/CFG-004_79 — CoreForge Thermogenic Fat Burner.png',
  '["/other/supp-images/CFG-004_79 — CoreForge Thermogenic Fat Burner.png"]'::jsonb,
  130, 4.5, 198, 'New', false, true,
  true, false, true,
  NULL, 60, NULL, NULL,
  NULL, NULL, NULL,
  'Contains stimulants. Not suitable for those with heart conditions or under 18.',
  NULL,
  ARRAY['Boosts metabolism','Increases energy','Supports fat loss','Preserves muscle mass','Controls appetite'],
  ARRAY['Green Tea Extract','L-Carnitine','60 Capsules','Metabolism Support'],
  NOW(), NOW()
),
(
  'CFG-026', 'CoreForge Thermogenic Complex',
  'thermogenic-complex',
  'Enhanced thermogenic formula with appetite control. Your complete fat loss solution.',
  'An upgraded thermogenic formula with added appetite suppressants and mood enhancers for comprehensive fat loss support. Perfect for those serious about getting lean.',
  'CFG-026', 'Recovery & Performance',
  89.00, NULL,
  '/other/supp-images/CFG-026_89 — CoreForge Thermogenic Complex.png',
  '["/other/supp-images/CFG-026_89 — CoreForge Thermogenic Complex.png"]'::jsonb,
  75, 4.6, 112, NULL, false, true,
  true, false, true,
  NULL, 60, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Advanced formula','Appetite control','Mood support','Complete fat loss'],
  ARRAY['Enhanced Blend','Appetite Support','60 Capsules','Premium Ingredients'],
  NOW(), NOW()
),
(
  'CFG-016', 'CoreForge Collagen Protein Blend',
  'collagen-protein-blend',
  'Support joints, skin, and connective tissue. Premium collagen for total body wellness.',
  'CoreForge Collagen Protein delivers types I, II, and III collagen to support joint health, skin elasticity, hair and nail strength, and overall connective tissue health. Perfect for athletes and anyone concerned with aging gracefully.',
  'CFG-016', 'Recovery & Performance',
  109.00, NULL,
  '/other/supp-images/CFG-016_109 — CoreForge Collagen Protein Blend.png',
  '["/other/supp-images/CFG-016_109 — CoreForge Collagen Protein Blend.png"]'::jsonb,
  85, 4.7, 167, NULL, false, true,
  true, false, true,
  500, 50, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Supports joint health','Improves skin elasticity','Strengthens hair and nails','Aids connective tissue','Anti-aging benefits'],
  ARRAY['Types I, II, III','Multi-Collagen','10g Per Serve','50 Servings'],
  NOW(), NOW()
),
(
  'CFG-017', 'CoreForge Protein + Greens Blend',
  'protein-greens-blend',
  'Protein plus superfoods. Complete nutrition in every scoop.',
  'Combine your daily protein and greens in one convenient shake. This blend contains premium whey protein plus a comprehensive greens blend including spirulina, chlorella, and wheat grass for complete nutrition.',
  'CFG-017', 'Recovery & Performance',
  139.00, NULL,
  '/other/supp-images/CFG-017_139 — CoreForge Protein + Greens Blend.png',
  '["/other/supp-images/CFG-017_139 — CoreForge Protein + Greens Blend.png"]'::jsonb,
  60, 4.6, 98, 'New', false, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Protein + superfoods','Complete nutrition','Antioxidant rich','Alkalizing greens'],
  ARRAY['20g Protein','Greens Blend','Superfoods','All-In-One'],
  NOW(), NOW()
),
(
  'CFG-018', 'CoreForge Recovery Protein Blend',
  'recovery-protein-blend',
  'Multi-phase protein with added recovery nutrients. Your complete post-workout solution.',
  'A specially formulated blend combining fast and slow-digesting proteins with added glutamine, creatine, and carbs for optimal post-workout recovery. Everything you need in one formula.',
  'CFG-018', 'Recovery & Performance',
  119.00, NULL,
  '/other/supp-images/CFG-018_119 — CoreForge Recovery Protein Blend.png',
  '["/other/supp-images/CFG-018_119 — CoreForge Recovery Protein Blend.png"]'::jsonb,
  70, 4.8, 156, NULL, false, true,
  true, false, true,
  NULL, 30, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Multi-phase protein','Added recovery nutrients','Includes creatine & glutamine','Complete post-workout'],
  ARRAY['Whey + Casein','Recovery Blend','30g Protein','All-In-One'],
  NOW(), NOW()
),

-- STACKS & BUNDLES
(
  'CFG-007', 'CoreForge Starter Stack',
  'starter-stack',
  'Perfect for beginners. Whey protein + creatine at a special bundle price.',
  'Everything you need to start your fitness journey. Includes our 1.5kg Whey Protein and 100g Creatine trial size. Perfect for first-time supplement users. Save 20% vs buying separately.',
  'CFG-007', 'Stacks & Bundles',
  69.00, 118.00,
  '/other/supp-images/CFG-007_69 — CoreForge Starter Stack.png',
  '["/other/supp-images/CFG-007_69 — CoreForge Starter Stack.png"]'::jsonb,
  50, 4.8, 189, 'Best Seller', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Perfect for beginners','Essential supplements','Save 20% vs separate','Everything to get started'],
  ARRAY['Whey 1.5kg','Creatine 100g','Beginner Friendly','20% Savings'],
  NOW(), NOW()
),
(
  'CFG-006', 'CoreForge Performance Stack Bundle',
  'performance-stack-bundle',
  'Complete performance package. Pre-workout, protein, and creatine for maximum gains.',
  'Our most popular stack includes Pre-Workout 30 serves, Whey Protein 2kg, and Creatine 500g. Everything you need for energy, recovery, and growth. Save 25% vs buying separately.',
  'CFG-006', 'Stacks & Bundles',
  179.00, 257.00,
  '/other/supp-images/CFG-006_179 — CoreForge Performance Stack Bundle.png',
  '["/other/supp-images/CFG-006_179 — CoreForge Performance Stack Bundle.png"]'::jsonb,
  65, 4.9, 267, 'Best Seller', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Complete performance package','Energy + recovery + growth','Save 25% vs separate','Most popular stack'],
  ARRAY['3 Products','Pre + Protein + Creatine','25% Savings','Best Value'],
  NOW(), NOW()
),
(
  'CFG-021', 'CoreForge Strength Duo',
  'strength-duo',
  'Maximize strength gains. Creatine 500g + Pre-Workout for unstoppable power.',
  'The ultimate strength combination. Our full-size Creatine Monohydrate paired with Pre-Workout for maximum strength and power output. Perfect for powerlifters and strength athletes.',
  'CFG-021', 'Stacks & Bundles',
  149.00, 138.00,
  '/other/supp-images/CFG-021_149 — CoreForge Strength Duo.png',
  '["/other/supp-images/CFG-021_149 — CoreForge Strength Duo.png"]'::jsonb,
  45, 4.8, 134, NULL, false, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Maximum strength focus','Creatine + pre-workout','Perfect for powerlifting','Bundle savings'],
  ARRAY['Strength Focus','2 Products','Power Stack','Athlete Approved'],
  NOW(), NOW()
),
(
  'CFG-012', 'CoreForge Ultimate Muscle Stack',
  'ultimate-muscle-stack',
  'Everything for serious mass. Whey, creatine, pre-workout, and BCAAs. Maximum results.',
  'Our most comprehensive muscle-building stack. Includes Whey Protein 2kg, Creatine 500g, Pre-Workout 30 serves, and BCAA Recovery. Everything you need for maximum muscle growth. Save 30%.',
  'CFG-012', 'Stacks & Bundles',
  249.00, 326.00,
  '/other/supp-images/CFG-012_249 — CoreForge Ultimate Muscle Stack.png',
  '["/other/supp-images/CFG-012_249 — CoreForge Ultimate Muscle Stack.png"]'::jsonb,
  35, 4.9, 198, 'Athlete Approved', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Complete muscle-building system','4 essential products','Save 30% vs separate','Maximum results'],
  ARRAY['4 Products','Complete System','30% Savings','Best For Mass'],
  NOW(), NOW()
),
(
  'CFG-013', 'CoreForge Lean Transformation Stack',
  'lean-transformation-stack',
  'Get shredded while maintaining muscle. Isolate, thermogenic, and BCAAs for cutting.',
  'Designed specifically for cutting phases. Includes Whey Isolate 2kg, Thermogenic Fat Burner, BCAA Recovery, and Lean Protein 1kg. Everything you need to get lean while preserving muscle. Save 25%.',
  'CFG-013', 'Stacks & Bundles',
  199.00, 346.00,
  '/other/supp-images/CFG-013_199 — CoreForge Lean Transformation Stack.png',
  '["/other/supp-images/CFG-013_199 — CoreForge Lean Transformation Stack.png"]'::jsonb,
  40, 4.8, 176, 'New', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Perfect for cutting','Preserve muscle while leaning','Complete fat loss system','Save 25% vs separate'],
  ARRAY['Cutting Stack','4 Products','Fat Loss Focus','25% Savings'],
  NOW(), NOW()
),
(
  'CFG-024', 'CoreForge Elite Performance Stack',
  'elite-performance-stack',
  'For elite athletes. Advanced pre-workout, isolate, creatine, and aminos.',
  'Our premium performance stack for serious athletes. Includes Advanced Pre-Workout 60 serves, Whey Isolate 2.5kg, Creatine 500g, and Amino Energy. The choice of champions. Save 30%.',
  'CFG-024', 'Stacks & Bundles',
  249.00, 516.00,
  '/other/supp-images/CFG-024_249 — CoreForge Elite Performance Stack.png',
  '["/other/supp-images/CFG-024_249 — CoreForge Elite Performance Stack.png"]'::jsonb,
  25, 4.9, 143, 'Athlete Approved', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Premium formulas','For elite athletes','Maximum performance','Save 30% vs separate'],
  ARRAY['Elite Stack','4 Premium Products','30% Savings','Pro Choice'],
  NOW(), NOW()
),
(
  'CFG-022', 'CoreForge Complete Transformation System',
  'complete-transformation-system',
  'Our ultimate package. 6 products for complete body transformation. Maximum value.',
  'The complete CoreForge experience. Includes Whey Protein 2kg, Whey Isolate 2kg, Pre-Workout, Creatine, BCAAs, and Thermogenic. Everything you could possibly need for a complete transformation. Save 35%.',
  'CFG-022', 'Stacks & Bundles',
  399.00, 495.00,
  '/other/supp-images/CFG-022_399 — CoreForge Complete Transformation System.png',
  '["/other/supp-images/CFG-022_399 — CoreForge Complete Transformation System.png"]'::jsonb,
  20, 4.9, 98, 'Best Seller', true, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Complete supplement system','6 essential products','Maximum value bundle','Save 35% vs separate'],
  ARRAY['6 Products','Complete System','35% Savings','Ultimate Value'],
  NOW(), NOW()
),
(
  'CFG-035', 'CoreForge Muscle Builder Kit',
  'muscle-builder-kit',
  'Mass-building essentials. Protein, creatine, and meal replacement for serious size.',
  'Perfect for those focused on building size. Includes Whey Protein 2kg, Creatine 500g, and Meal Replacement. Everything needed to stay in a caloric surplus and build serious mass.',
  'CFG-035', 'Stacks & Bundles',
  189.00, 307.00,
  '/other/supp-images/CFG-035_189 — CoreForge Muscle Builder Kit.png',
  '["/other/supp-images/CFG-035_189 — CoreForge Muscle Builder Kit.png"]'::jsonb,
  30, 4.7, 87, NULL, false, true,
  true, false, true,
  NULL, NULL, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Mass-building focus','Easy surplus calories','Complete nutrition','Great value'],
  ARRAY['Bulking Stack','3 Products','Mass Gain','Value Bundle'],
  NOW(), NOW()
),

-- SAMPLES
(
  'CFG-028', 'CoreForge Protein Sample Sachet',
  'protein-sample-sachet',
  'Try before you buy. Single-serve protein sample in your choice of flavor.',
  'Not sure which flavor to choose? Try our single-serve sample sachets. Each contains one full serving of our premium whey protein. Perfect for testing flavors before committing to a full tub.',
  'CFG-028', 'Samples',
  5.00, NULL,
  '/other/supp-images/CFG-028_5 — CoreForge Protein Sample Sachet.png',
  '["/other/supp-images/CFG-028_5 — CoreForge Protein Sample Sachet.png"]'::jsonb,
  500, 4.6, 234, 'New', false, true,
  true, false, true,
  NULL, 1, NULL, NULL,
  NULL, NULL, NULL, NULL, NULL,
  ARRAY['Try before buying','Test flavors','Single serving','Low commitment'],
  ARRAY['Sample Size','1 Serving','Multiple Flavors','Perfect For Testing'],
  NOW(), NOW()
)

ON CONFLICT (id) DO NOTHING;
